### ISSUE TITLE
Crash on install

### ISSUE THREAD

**Issue by Imiona** [ALIENQuake/ProjectInfinity#12]
I get this Error when trying to install PI

Problemsignatur:
  Problemereignisname:	CLR20r3
  Problemsignatur 01:	ProjectInfinity.exe
  Problemsignatur 02:	0.7.6.0
  Problemsignatur 03:	5d19a067
  Problemsignatur 04:	PoshExeHostWinV5
  Problemsignatur 05:	0.7.6.0
  Problemsignatur 06:	5d19a067
  Problemsignatur 07:	3c
  Problemsignatur 08:	87
  Problemsignatur 09:	System.IO.FileNotFoundException
  Betriebsystemversion:	6.1.7601.2.1.0.768.3
  Gebietsschema-ID:	3079
  Zusatzinformation 1:	e6e6
  Zusatzinformation 2:	e6e6c208b90db2aa028f8f653cabbf23
  Zusatzinformation 3:	d770
  Zusatzinformation 4:	d770a8d56ee6172770911a2e2e812f59

**Comment by ALIENQuake** [comment]
@Imiona I see that you have Windows 7, did you installed  .NET Framework 4.5.2 or above and Powershell 5.1?

**Comment by Imiona** [comment]
Yes, i have the newest NET but i just saw i have Powershell Version 1.0 ! Now i wanted to update it, but the Update (Win7-KB3191566-x86.msu) says  that "This update is not eligable for this Computer".

Never had that happening beore. Is this because i have such an old Version of PS installed? What can i do now?

**Comment by ALIENQuake** [comment]
@Imiona Is you Windows 7 is 64-bit? If yes, you should use Win7AndW2K8R2-KB3191566-x64.ZIP according to https://docs.microsoft.com/en-us/powershell/wmf/setup/install-configure

**Comment by Imiona** [comment]
Fixed
