### ISSUE TITLE
Mod component selection does not work on offline computer

### ISSUE THREAD

**Issue by ckoegit** [ALIENQuake/ProjectInfinity#13]
Windows 10, 64 bit, current patchlevel

Logs hopefully attached ! 
[Logs.zip](https://github.com/ALIENQuake/ProjectInfinity/files/3931556/Logs.zip)

Trying to mod IWD:EE. Extracted mods detected correctly in their folder, but could not expand component subtree view and/or select components. After clicking mod vanished from selection window.

Inspecting the logs (2019.12.06-10꞉41 or2019.12.06-10꞉37) it appears Project Infinity tries to download weidu.exe from the net and failed because the computer was offline at that time. I am also not sure what the "standard local path" for weidu.exe referenced in the log might be, it is not documented it appears. I assume without a working weidu.exe it cannot read the tp2 files.

If the computer is brought online (2019.12.06-10꞉39) component selection works and there are no errors in the logs.

**To Reproduce**
Set computer offline and not having a "standard local path" weidu.exe should reproduce the behaviour.

**Expected behavior**
- Documenting that online download of "weidu.exe" might happen and documentation of the "standard local path" (which I hope I did not miss)
- A clear/prominent error message "No weidu.exe found" or similar instead of not opening the component selection sub-tree-view and just removing the mod from the list.
- Ideally a dialogue choice or preference/configuration setting for local weidu.exe

**Comment by ALIENQuake** [comment]
This will have to wait for next release.

**Comment by ALIENQuake** [comment]
@ckoegit Done. PI will now use a local version of weidu if there is no internet connection, a message box should tell where you shall put weidu executable and there is a new wiki page: https://github.com/ALIENQuake/ProjectInfinity/wiki/Using-Project-Infinity-offline.

**Comment by ckoegit** [comment]
Thank you !
