### ISSUE TITLE
Sorting order file does not work for A#7ImprovedShamanicDance mod

### ISSUE THREAD

**Issue by ckoegit** [ALIENQuake/ProjectInfinity#14]
**Check requirements:**
Windows10, 64 bit, current patchlevel

**Upload logs from Logs folder**
Attached. Also attached is a screenshot which hopefully shows what the problem is.
[Logs.zip](https://github.com/ALIENQuake/ProjectInfinity/files/3941191/Logs.zip)

Preliminary Remarks:
When you check the logs you will see that I had to cancel an installation once after hitting "Start-Installation" instead of "Apply-Sorting Order", but I assume that is not a factor for the bug described below. However, the button layout might be a usability/ GUI design issue in general.

I selected "SoD" as game, I believe this is wrong and should be "BG:EE", but believe that is also unconnected to the bug.

**Describe the bug**
The sort order from the file open in the screenshot is not applied to the A#7ImprovedShamanicDance mod components. They end up in the unsorted category. The sort order file works fine for everything else. At the moment I would assume that the hash mark "#" in the mod name breaks the file parsing.

Also, "Warning" appears to be misspelled as "Warring".

**To Reproduce**
Get the mod and try a sort order file. The sort order file used is attached.
[MY_BGEE_sort_order.txt](https://github.com/ALIENQuake/ProjectInfinity/files/3941201/MY_BGEE_sort_order.txt)

**Expected behavior**
Mod is correctly sorted in install order as specified in the sort order file.

**Screenshots**
![a7_project_infinity](https://user-images.githubusercontent.com/58590878/70462838-03507600-1abc-11ea-8e43-8c3a0b15c675.png)

**Comment by ALIENQuake** [comment]
@ckoegit Reported some time ago and fixed for 0.7.9  :)

**Comment by ckoegit** [comment]
Thank you. I will wait for 0.7.9 to become available then for my next try.

In this case the "*" wildcard would not work because that would include component 40 (Shaman-specific items for IWD:EE) as far as I understand the possible variants ? I will re-read the documentation.

I generated the sort order from a mostly up to date BWS-type InstallOrder.ini with just egrep/awk, so not much effort with it the way it is :-)

**Comment by ALIENQuake** [comment]
> In this case the "*" wildcard would not work because that would include component 40 (Shaman-specific items for IWD:EE) as far as I understand the possible variants ? I will re-read the documentation.
**The Sorting Order feature doesn't add any mods/components to the installation sequence.**

**Comment by ckoegit** [comment]
Yes, I vaguely remember now. There is some kind of (not very prominent) warning if the sort order does not match the component selection I think ? 
I first made the sort order file and then selected the components according to that. Having two unaligned lists, i.e. selection and sort order, feels somehow strange to me. Would it not be possible to select components according to the sort order file (perhaps only if it is explicit enough, e.g no wildcards or so ?).
I will give the tool another try as soon as 0.7.9 is released, at the moment it does not install the mods I want.

**Comment by ALIENQuake** [comment]
@ckoegit Two lists are essentially a "correct install order of the mods" and "mods, which I want to install for the current game". Combining two into one convert it into a simplified version of 'weidu.log' with all it's limitation.


> I will give the tool another try as soon as 0.7.9 is released, at the moment _it does not install_ the mods I want.

Which mods aren't installed?

**Comment by ckoegit** [comment]
> Two lists are essentially a "correct install order of the mods" and "mods, which I want to install for the current game". Combining two into one convert it into a simplified version of 'weidu.log' with all its limitation.

I assume you write "limitation" because your design is to have a "universal" sort order file and then just select components on top ? If yes: can that sort order file be truly completely independent of the selected mods ?  Probably that has been discussed to death already, so I accept that if it is the case.

But to me not being able to tell the program optionally "use the sort order to select components" feels strange and limiting as I wrote. The risk at least is divergences in selection and sort order. 
The current warning (if I remember correctly at all) is too easy to miss eventually.

> Which mods aren't installed 

Well, the one mentioned in the subject. I did not test it I admit, writing "it does not install the mods I want" is   too strong wording then. But:

I cannot set  its  position in my sort order file obviously. With that I am not sure when it would be installed. Eventually randomly or at the start before all others or at the end after all others ? I do not know from the GUI and I have no way to check in advance. There is no obvious way to load a sort order file and then modify the loaded sort order (I could find). 
I could actually run the whole install (waiting several hours) but expect that I get a messed up install. 

I am quite happy with my BWP install right now. So this is by no means important (or urgent). So please do not worry !

**Comment by ALIENQuake** [comment]
@ckoegit 
I will think about a more direct way to inform players regarding failed sorting.

> There is no obvious way to load a sort order file and then modify the loaded sort order (I could find).

There is - simply cut and paste install sequence data after sorting. Then immediately click "Start-Installation" button.

Anyway, this is fixed by 0.7.9.
