### ISSUE TITLE
[Feature request] Program should be portable

### ISSUE THREAD

**Issue by SylwesterZarebski** [ALIENQuake/ProjectInfinity#17]
**Check requirements:**
 - OS: Windows 10 x64
 - .NET Framework version: 4.8
 - Powershell version: 5.1.18362.752

**Upload logs from Logs folder**
Not relevant

**Describe the bug**
Program downloads files to AppData and change registry and it should not.
All downloads should go to subdirectory relative to program path and do not change registry.

**To Reproduce**
1. Run program.

**Expected behavior**
Program should be self contained and do not touch any other directories, especially registry.

**Comment by ALIENQuake** [comment]
@SylwesterZarebski I'm assuming that you also need Git as 'portable', right?

**Comment by SylwesterZarebski** [comment]
Yes, everything used should be self-contained in portable directory. But git has portable versions from what i can see in search engines.

**Comment by ALIENQuake** [comment]
@SylwesterZarebski Implemented in 0.8.5. PI is fully portable out-of-the-box. Future tools will also be used from \Tools directory.

**Comment by SylwesterZarebski** [comment]
Thanks a lot, i'll check it :-)
