### ISSUE TITLE
Windows Defender finds trojan in ProjectInfinity.exe

### ISSUE THREAD

**Issue by Shtepser** [ALIENQuake/ProjectInfinity#19]
When running the downloaded .exe, Windows Defender alerts that ProjectInfinity.exe contains Trojan (Trojan:Script/Wacatac.B!ml).
Why this happens and how it could be fixed?

**Comment by ALIENQuake** [comment]
Hi @Shtepser It's a false positive but since Windows Defender is so widely used, I've reported this directly to Microsoft.

**Comment by ALIENQuake** [comment]
@Shtepser Microsoft removed detection, to update your local WD do:
```
1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
3. Run "MpCmdRun.exe -SignatureUpdate"
```

**Comment by Shtepser** [comment]
@ALIENQuake It worked, thanks!

**Comment by GraionDilach** [comment]
This is back with a Trojan:Win32/AgentTesla!ml claim.

**Comment by ALIENQuake** [comment]
@GraionDilach Newest report: https://www.virustotal.com/gui/file/ad8b92e5ee8a054f9ba380ea019ea9e2ba9dfe47dbb5aeb35d92cd01b4a78555/detection
Which AV?

**Comment by GraionDilach** [comment]
WinDefender which is why I'm asking for a reopen and not opening a new one.

**Comment by ALIENQuake** [comment]
@GraionDilach Try Update-MpSignature and redownload.

**Comment by GraionDilach** [comment]
Seems that broke WinDefender (since I deleted my previous engine as your previous post suggested and apparently the update throws me an error and currently I'm at a point where I need to grab an install media and do an offline system verification check to get that fixed assuming I'm lucky and doesn't need a complete sys reinstall).

**Comment by GraionDilach** [comment]
Also FYI: taking the 0.9.3 download and throwing it to VirusTotal triggered Kaspersky for me, although when I look at content MD5, it recognizes and links to your upload. https://www.virustotal.com/gui/file/3dade8ba382a317568db6820c9efb093375acbcd8002956a5dd5f5cd8430589a/detection

**Comment by ALIENQuake** [comment]
This command shouldn't break the WinDef, it's just to update definitions. The Kaspersky AV didn't respond to the false-positive report last time when it falsely detects PI. At this point, I don't know what I can do.
