### ISSUE TITLE
GUI freaks out over a forward slash difference between URLs

### ISSUE THREAD

**Issue by RobertPeetsalu** [ALIENQuake/ProjectInfinity#20]
**Check requirements:**
 - OS: 64-bit, fully updated Windows 10

**Describe the bug**
The download URL of the Unfinished Business mod for BG2 has a forward shash at the end, but it's gitRemoteOriginUrl doesn't, which triggers a warning to seek help in forums.

**To Reproduce**
1. Open Project Infinity 0.8.12
2. Press the green button
3. Download the Unfinished Business mod from the list of Pocket-Plane-Group mods
4. See "WARRNING!
The update was detected but there is a mismatch betwen INI Download data and local update link:
Warning! Download: https://github.com/Pocket-Plane-Group/UnfinishedBusiness/ not match gitRemoteOriginUrl: https://github.com/Pocket-Plane-Group/UnfinishedBusiness
Warning! possible cause: online mod repository was renamed or transfered
Warning! it's impossible to preform update check and delta updates
Warning! please ask for support at the forums."

**Expected behavior**
No warning and no forward slash at the end of the download link.

**Screenshots**
![image](https://user-images.githubusercontent.com/892058/105786079-05f28100-5f85-11eb-8d3d-b51ed4b8510b.png)

**Comment by ALIENQuake** [comment]
@RobertPeetsalu Thanks for the report, I've sent PR for UB but I will also handle this internally.

**Comment by ALIENQuake** [comment]
@RobertPeetsalu This should be now fixed with 0.8.13
