### ISSUE TITLE
The app appearance is buged with non default window scaling

### ISSUE THREAD

**Issue by kostiya** [ALIENQuake/ProjectInfinity#24]
**Check requirements:**
 - OS: should be 64-bit, fully updated Windows 7, 8.1 or 10
 - .NET Framework version: should be 4.5.2 or above [Download](https://www.microsoft.com/net/download/dotnet-framework-runtime)
 - Powershell version: should be Powershell 5.1 [Download](https://docs.microsoft.com/en-us/powershell/wmf/setup/install-configure)

**Upload logs from Logs folder**
Not needed

**Describe the bug**
Shown in screenshot.
This is with 150% window scale on 4k display.

**To Reproduce**
Open the app

**Expected behavior**
The text should be readable.

**Screenshots**
<img width="841" alt="2021-07-20 23_22_23-Project Infinity 0 9 6" src="https://user-images.githubusercontent.com/6069887/126390904-076453f6-706e-4ea4-8919-b8afa52c3634.png">

**Comment by kostiya** [comment]
Used windows Enhanced scaling on app compatibility option.
Now it's blurry, but the app runs great.

**Comment by ALIENQuake** [comment]
@kostiya It's a known bug. Your workaround is the only thing that can help right now.
