### ISSUE TITLE
AV and Smartscreen issues

### ISSUE THREAD

**Issue by Naxterra** [ALIENQuake/ProjectInfinity#25]
Hello

App is classified as Trojan.GenericKD.46892447 by Bitdefender and Windows Smartscreen is blocking it. Even when I put it into exclusion list, it first tried to write something in registry. Why?

I denied registry access and then my AV blocked C:\Temp\Infinity Engine Mod Package.dat with detection name ATC.SuspiciousBehavior.73F6F2DE54014AF5.

**Comment by ALIENQuake** [comment]
@Naxterra It's nothing more than false positive. If you AV report that PI is a virus, open the CHECKSUM.md file and verify the ProjectInfinity.exe SHA256 file hash using this command: `Get-FileHash -Algorithm SHA256 .\ProjectInfinity.exe` and you should get the same value.
