### ISSUE TITLE
Load Order Check Button [Feature]

### ISSUE THREAD

**Issue by yGKeKe** [ALIENQuake/ProjectInfinity#26]
Currently, this program appears to scan everything, every single time you click on anything. It literally takes several minutes just to expand a section in the mod list sometimes because of all the background shit the program does every single time you click on anything.

Whatever it's doing, it should only be doing it after you click on a dedicated button, AFTER you enable all of your mod components. The constant stateful re-checking of literally everything makes this program run like a hippo in quick-sand.

**Comment by ALIENQuake** [comment]
I'm currently rewriting a large part of the app to improve responsiveness, next version should be much faster.

**Comment by ALIENQuake** [comment]
Implemented in [0.10.0](https://github.com/ALIENQuake/ProjectInfinity/releases/tag/0.10.0)
