### ISSUE TITLE
Front-End Fixes

### ISSUE THREAD

**Issue by yGKeKe** [ALIENQuake/ProjectInfinity#27]
The text is cut off on the left-side list...This might only be on my set-up and not affecting everyone, but it's still an issue.

The buttons at the top are also misaligned. This is obviously not a use-limited issue and only an aesthetic one.

Both issues visable in image:

![image](https://user-images.githubusercontent.com/55903550/168927029-da25b682-ef59-4106-a249-a1d0c261b72c.png)

**Comment by ALIENQuake** [comment]
Please check pinned issue: https://github.com/ALIENQuake/ProjectInfinity/issues/24
