### ISSUE TITLE
Why there is no source code?

### ISSUE THREAD

**Issue by journeym** [ALIENQuake/ProjectInfinity#30]
It would be nice to share source, it's possible someone contributed to this, it's clearly not in any kind of usable state except demo.

**Comment by ALIENQuake** [comment]
If this wasn't known before: contributions are welcomed, yet source code must stay closed for various reasons.

**Comment by jameskirsch** [comment]
Hey, I was just looking for the source, I just wanted to see if I could add a root node checkbox for "select all" on the branches for the Mod List Tree. The reason I was looking to do this is because it seems painfully slow with a lot of mods right now, so that is more of a temporary solution to that

**Comment by ALIENQuake** [comment]
@jameskirsch Hi, the issue with selecting slowdowns is fixed. But the 'Select All' feature is not something that I will implement because of my previous experience with how people use such feature: Select all mod components, who cares what those components do => Och no, my game is broken => Report false bug etc

**Comment by journeym** [comment]
> @jameskirsch Hi, the issue with selecting slowdowns is fixed.
Hmm, i have used 0.9.9 and it isn't. When selecting component, is stil recalculates all the references and this stacks progressivly, impossible to work after 50+ selected components.
That's why i opened this case actually, im unable to select multiple mods with lots of components.

**Comment by alycecil** [comment]
So whos feet did you step on, or worse what are you actually doing in the exe that the code must stay closed?

**Comment by i30817** [comment]
Besides the obvious reasons, this project dependence on powershell and probably on WMF means it can't be used on wine, so no linux modding with it.

**Comment by sfaria** [comment]
> If this wasn't known before: contributions are welcomed, yet source code must stay closed for various reasons.

And those reasons are? How does one contribute without source? It's really hard to want to trust a closed-source program that gets flagged as a virus on scanners, by the way.

**Comment by CamilleHbp** [comment]
No source code? This is a terrible practice from another age. There are no reasons to do so for a non-profit project. This is a terrible idea and dooms the project if you ever stop it.

Why did you even setup a Github repository if you only host the .exe?

It also prevents a lot of users from using it for trust issues, especially when you get a `Trojan:Win32/Powbr.A!MTB` warning when you launch the .exe. Goodbye.

**Comment by ALIENQuake** [comment]
@CamilleHbp 
I use GitHub to receive feedback from people outside of the IE community sites and forums. I didn’t want to bring any drama into GitHub, but it seems that it’s unavoidable. So, here’s what’s going on:

There are valid reasons for keeping the source code closed. The most important one is that there is a malicious actor in the Infinity Engine Modding community who has hijacked the previous mod manager and replaced mods with customized versions. This person promotes their own mods by recommending them over others and gatekeeps mods that interfere with their content. I apologize for not being more transparent about this earlier.

Additionally, here are the words from the Windhawk and 7TaskbarTweak dev:
![image](https://github.com/ALIENQuake/ProjectInfinity/assets/365255/6fd5272a-a925-4cc5-b065-991d00189b90)

So my stance is unchanged: You don't need source code to be open to trust the application and contribute to it.

I'm closing this discussion and replacing it with a new one with a clear explanation of the reasons.

**Comment by GraionDilach** [comment]
@ALIENQuake Maybe also lock this one (and even the other one) to prevent further reiterations of the point - some of us explained the historical reason on the IE Discord in parallel.
