### ISSUE TITLE
Windows 11 support?

### ISSUE THREAD

**Issue by lukasz-pekala** [ALIENQuake/ProjectInfinity#31]
**Computer**
 - OS: Windows 11
- [/] .NET Framework version: should be 4.5.2 or above [Download](https://www.microsoft.com/net/download/dotnet-framework-runtime)
 - [/] Powershell version: should be Powershell 5.1 [Download](https://docs.microsoft.com/en-us/powershell/wmf/setup/install-configure)

**Upload logs from Logs folder**
Logs folder is not even created

**Describe the bug**
Application won't run on Windows 11. Switching compatibility mode does nothing. No GUI is displayed. No Logs folder created

**Comment by ALIENQuake** [comment]
@lukasz-pekala The app runs fine on Windows 11, check Windows Defender and add process and file exclusion.
