### ISSUE TITLE
Importing weidu log no longer works

### ISSUE THREAD

**Issue by eXistenZe** [ALIENQuake/ProjectInfinity#34]
**Describe the bug**
After the last updates, importing a weidu log no longer sets the load order and the install gives this warning.
![image](https://user-images.githubusercontent.com/26518879/178487346-5cb072de-b519-47b1-b5f8-14ed3d20a623.png)

**Comment by ALIENQuake** [comment]
Importing weidu.log only checks mod checkboxes, it doesn't re-arrange mod at the mod list. You have to do this by yourself or use an alternative solution: after importing weidu.log, you need to copy/export the install sequence, and uncheck all mods using '**X**' button at the left-bottom, then import the install sequence again and immediately start the installation.
