### ISSUE TITLE
[Feature]Allow ignoring warnings and errors

### ISSUE THREAD

**Issue by eXistenZe** [ALIENQuake/ProjectInfinity#41]
**Describe the solution you'd like**
Every warning and error causes the install to pause and wait for user input.
Sometimes I want to test an install during the night and check everything in the morning, even if there are dozens of errors.
The app could have the option to never pause the install.

**Comment by ALIENQuake** [comment]
There are two experimental ini settings:
```
ExpDisablePauseOnWarning = true
ExpDisablePauseOnError = true
```
You can use them but remember that error reporting is essential for modders to fix them.

**Comment by eXistenZe** [comment]
Thanks
