### ISSUE TITLE
Selected mods tick resetting

### ISSUE THREAD

**Issue by arosenow** [ALIENQuake/ProjectInfinity#48]
Hi, I occasionally experience an issue where many, but not all, of the mod selections reset whilst using the app. I export my selections to be safe, however it seems if they unselect without me noticing and then I save I lose my progress

**Comment by ALIENQuake** [comment]
@arosenow That's expected behavior when the mod doesn't support globally unique labels. You can check this info on the mod info panel.

**Comment by arosenow** [comment]
So the ultimate solution would be for all the mod authors to add labels. It's a shame as for the time being it limits the utility of the tool

**Comment by ALIENQuake** [comment]
@arosenow That's true. But at the same time, it protects you from unintended changes to your 'mod list' after mod updates. Omitting previously saved mods from your 'saved mod list' or installing ones you didn't tick previously is a much bigger problem.

**Comment by arosenow** [comment]
I've created an "at my own risk" hack, as I'll typically just be downloading and installing once, given changing mods post install breaks the saves. I iterate through all the mods and insert labels if they don't exist

**Comment by arosenow** [comment]
I can confirm it's not just mods that don't have labels unticking. SCS resets all components after you refresh to add new mods you've added to the folder, although the components are still listed in the install sequence

**Comment by arosenow** [comment]
It appears to be 2 mods in my setup that aren't saving. Sword Coast Strategems and Tweaks and Tricks. Both provided their own .ini and Labels. All the ones using my mod patcher appear to work fine. They load maybe 1 or 2 components and then forget the rest

**Comment by ALIENQuake** [comment]
@arosenow You also need to have LabelType = GloballyUnique
Reffer to: https://github.com/ALIENQuake/ProjectInfinity/wiki/Adding-metadata-for-mod
and https://www.gibberlings3.net/forums/topic/32516-tutorial-what-is-label

**Comment by arosenow** [comment]
My patching software is working with PI and makes mods that don't have labels work, it was because 3rd party mods who do their own labels don't all apply them to all the components and sometimes leave LabelType commented out. Eg SCS only labels the 1st 2
