### ISSUE TITLE
Weidu Requesting input after "wrong argument"

### ISSUE THREAD

**Issue by arosenow** [ALIENQuake/ProjectInfinity#49]
Below is an example, the mod it occurs during appears to be arbitrary as I've experimented with disabling several. 
I'll have to disable all mods in my quest folder and try incrementally, but not sure what feature of mods is causing this

//SUCCESSFULLY INSTALLED      Finish Cordyr's Quest without killing Sil
//[F:\Mods\BG2\EE-Mod-Setup-master\Project Infinity\Tools\WeiDU\249.00\weidu.exe] WeiDU version 24900
//F:\Mods\BG2\EE-Mod-Setup-master\Project Infinity\Tools\WeiDU\249.00\weidu.exe: wrong argument `--log'; option `--force-install' expects an integer.
//		WeiDU (version 24900: "Master Doom")
//usage: WeiDU [options] BAF,BCS,D,DLG,TRA,TP,TP2-files
//General Input Options:
//  --game X	set main game directory to X
//  --game-by-type X	set main game directory to the one where X is installed (BG,BG2,IWD,IWD2,PST)
//  --nogame 	do not load any default game files

**Comment by ALIENQuake** [comment]
@arosenow Please zip and share logs from Logs folder.

**Comment by arosenow** [comment]
I believe I've found the cause, the error was occurring in the mod installing immediately before bg1npc which I had forgot to tick a prerequisite component. So whilst I was unticking where the log ended it was happening in the next mod
