### ISSUE TITLE
Can't start on windows 10

### ISSUE THREAD

**Issue by jcvignoli** [ALIENQuake/ProjectInfinity#50]
Hi,
Since recent windows 10 updates (I guess .Net was also updated) I can't start PI anymore.
I just click on the exe, I can see the process starting, and then it closes (PI interface is not displayed though).
No log, nothing to report with, unfortunately.

**Comment by GraionDilach** [comment]
Combine Process Exception with File or Folder Exception within Windows Security.

**Comment by jcvignoli** [comment]
Thank you. Was indeed an issue with Windows Security!
