### ISSUE TITLE
Latest version won't launch

### ISSUE THREAD

**Issue by enderandrew** [ALIENQuake/ProjectInfinity#51]
**Check requirements:**
 - OS: Windows 11 64-bit
 - .NET Framework version:     • .NET SDK 7.0.306
    • .NET Runtime 7.0.9
    • ASP.NET Core Runtime 7.0.9
    • .NET Windows Desktop Runtime 7.0.9
 - Powershell version: should be Powershell 5.1 - Have both the built-in 5.1 and Preview 7.4

**Upload logs from the Logs folder**
Won't launch and no logs created

**Describe the bug**
Won't launch at all. It appears in Task Manager for half a second and it is gone. There is no log created, nothing in Windows Event Viewer, etc.

**To Reproduce**
1. Attempt to launch latest executable

**Expected behavior**
The application would launch

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

https://i.imgur.com/rCFAkBh.png

**Comment by ALIENQuake** [comment]
@enderandrew Did your Windows get an update recently? Please check Windows Defender.

**Comment by enderandrew** [comment]
Edit: I added a Process exclusion for ProjectInfinity.exe in Windows Defender, and sure enough the app is launching now. It is weird that the folder exclusion wasn't good enough but I already had an exclusion telling Defender to ignore everything in D:\BWS\ where I have everything.

**Comment by ALIENQuake** [comment]
Yep, process exclusion is required unfortunately.
