### ISSUE TITLE
Crash on Windows 7

### ISSUE THREAD

**Issue by Felipefpl** [ALIENQuake/ProjectInfinity#53]
@ALIENQuake - I have .net 4.8 and i get a crash when clicking 2x on windows 7, i wish i could help more. If i may add an suggestion i'd like to recommend a tool like bugtrap here on github to create full zipped crash logs. I'll attach them here in case that happens.

**Comment by ALIENQuake** [comment]
@ALIENQuake Have you installed prerequisites? For Windows 7, you need also https://learn.microsoft.com/en-us/powershell/scripting/windows-powershell/wmf/setup/install-configure?view=powershell-5.1

**Comment by Felipefpl** [comment]
I downloaded wmf 5.1 and powershell 7 and that worked, thanks for the help. :+1: 

Btw, why the program doesnt come with all folders needed and needs to download stuff? This isnt usual.

**Comment by ALIENQuake** [comment]
@Felipefpl All those extra files aren't required for Windows 10/11.

**Comment by Felipefpl** [comment]
I see, thanks for the info.
