### ISSUE TITLE
[Feature] To avoid losing components after re-opening, saving a copy to text of selected components where mods don't support globally unique labels

### ISSUE THREAD

**Issue by Kuiriel** [ALIENQuake/ProjectInfinity#54]
**Is your feature request related to a problem? Please describe.**
I'm frustrated when each time I re-launch Project Infinity many of the mod components that I previously selected are now unticked. This means that I must do my PI install in a single sitting, which may take hours.

I realize that saving components is listed as not possible where mods don't support globally unique labels. Is there a work around for this? If I could just select and copy the text to a document it would save time when I'm going back in to do it for the umpteenth time.

**Describe the solution you'd like**
Either some way to export to string or drag to select and thus copy-paste the list of components in the left window. Alternatively, any sort of hack or option to leave any selected components ticked when the program is shut and re-opened. 

**Describe alternatives you've considered**
Presently I'm just going to start taking photographs or short videos of the screen, I don't know why I didn't think of that earlier.

**Comment by Kuiriel** [comment]
Alright, I'm a doofus. It's right there in export/import install sequence. For some reason I've seen that many times but always thought it would re-tick things for me. I didn't realize it actually listed everything I ticked, that he selected components are listed in the strings on the right, I just have to follow that list to retick things.

Thank you, this will save time.

**Comment by GraionDilach** [comment]
You can copy-paste also generated install orders. Just Ctrl-A Ctrl-C the content after the generation.
