### ISSUE TITLE
[Feature]Recognition of mods

### ISSUE THREAD

**Issue by Mantoise** [ALIENQuake/ProjectInfinity#58]
Howdy, I don't know if I should post it here or post it at all but I noticed that three mods present in my folder aren't showing in the selectable list. This mods being Sheena, DragonShape, Kitanya. Am I mounting too many mods(230ish)? Is it because of their coding? Can they be added? Is there a simpler solution that I'm not seeing because I'm ignorant?

**Comment by ALIENQuake** [comment]
@Mantoise Hi, sometimes the mods aren't detected on the first scan or when there are 200+ mods in the mods directory. Can you  try rescan and report back? Or try to add one extra top-level folder for those mods.

**Comment by Mantoise** [comment]
I did that, the rescan still doesn't show them :'(
Edit: Sheena shows, the others don't

**Comment by ALIENQuake** [comment]
@Mantoise Kitanya mod seems to have .exe installer so it needs to be 'installed' into the clean dir and moved into 'Mods' folder. I can't find DragonShape mod.

**Comment by Mantoise** [comment]
I found the .zip [here](https://forums.beamdog.com/discussion/31888/dragon-shape-for-dragon-disciples)  it's named ddiscshp tp2.zip
Thank you, Alien

**Comment by ALIENQuake** [comment]
@Mantoise DragonShape also needs one extra top-level folder.
