### ISSUE TITLE
Install Error Wrong Argument Expects An Integer with No Choice Options

### ISSUE THREAD

**Issue by Mycenius** [ALIENQuake/ProjectInfinity#64]
I have this error in my current PI EET install process. Looks like it finished the G3 BG 2 Romances Mod, and is waiting to start next component (The Gibberlings Three Anniversary Mod)? I assume its the initialisation of the Anniversary Mod it's got the invalid --log argument for (not the completed Romance Mod)?

I presume its the mod data at fault, however should this show what the response choices/options are? What is the correct response to this, is it mod dependent?

I saw this same issue in previous bug report [Weidu Requesting input after "wrong argument" #49](https://github.com/ALIENQuake/ProjectInfinity/issues/49) which is similar, however my instance is not related to a missing mod component from the install sequence, as this mod only has a single component to install.

```
//Copying and patching 1 file ...
//Copying 1 file ...
//[.\lang\en_us\dialog.tlk] created, 298671 string entries
//SUCCESSFULLY INSTALLED      Date Night, by SisterVigilante
//[D:\Baldurs Gate EET Install 1\Project Infinity EET1\Tools\WeiDU\249.00\weidu.exe] WeiDU version 24900
//D:\Baldurs Gate EET Install 1\Project Infinity EET1\Tools\WeiDU\249.00\weidu.exe: wrong argument `--log'; option `--force-install' expects an integer.
//		WeiDU (version 24900: "Master Doom")
//usage: WeiDU [options] BAF,BCS,D,DLG,TRA,TP,TP2-files
//General Input Options:
//  --game X	set main game directory to X
//  --game-by-type X	set main game directory to the one where X is installed (BG,BG2,IWD,IWD2,PST)
//  --nogame 	do not load any default game files
//  --search X	look in X for input files (cumulative)
//  --search-ids X	look in X for input IDS files (cumulative)
//  --tlkin X	use X as DIALOG.TLK
//  --ftlkin X	use X as DIALOGF.TLK
//  --use-lang X	on games with multiple languages, use files in lang/X/
//  --tlkmerge X	merge X into loaded DIALOG.TLK
//		Press Enter For More Options
//  --yes 	answer all TP2 questions with 'Yes'
//  --uninstall 	answer all TP2 questions with 'Uninstall'
//  --reinstall 	reinstall all installed TP2 components
//  --language X	Set the language to X
//  --force-install 	X installs component X number (cumulative)
//  --force-uninstall 	X uninstalls component X number (cumulative)
//  --force-install-rest 	X Y... installs component number X, Y... (cumulative)
//  --force-install-list 	X Y... installs component number X, Y... (cumulative)
//  --force-uninstall-rest 	X Y... uninstalls component number X, Y... (cumulative)
//  --force-uninstall-list 	X Y... uninstalls component number X, Y... (cumulative)
//  --quick-menu 	X installs the quick menu selection X
//		Press Enter For More Options
```

Running on Windows 11 Pro 64-bit, etc.

Many TIA

**Comment by Mycenius** [comment]
I have worked around this by simply 'clicking through' (enter/return) on every instance of this message (leaving the response blank) and unpausing when the end of that particular mod was reached. I presume this is an issue with the mod data or related mods rather than PI itself?

I will close this report as the workaround above has worked for me.

**Comment by GraionDilach** [comment]
You ended up with a mod in your install order which doesn't exist (and/or a mod has been damaged within the PI mod download folder) leading to WeiDU unable to autodetect the tp2 and falling back to the generic behaviour.

Needs more info on knowing what went wrong.

**Comment by Mycenius** [comment]
Thanks for the clarification. I think a couple of this instances I also may have caused the issue as somewhere along the way I opened a txt file (of my import sequence) in Excel and saved as csv and I think Excel did its favourite trick of adding " " wrappers around some lines of text (where there were existing " or ' present).

PI detected some as mod not found at start of install which I resolved by editing those lines but I later found there were more lines with those Excel "  " wrappers that PI didn't report as not found at start of installation, so suspect some of the above errors I had were caused by those perhaps?

However I've run the install sequence twice more now and got the same error with a couple of the remaining mods. So will investigate further with the mod authors.

**Comment by GraionDilach** [comment]
If you want to keep the install order around in an external document (a good choice!), I'd suggest opting for a plaintext TXT instead of a CSV with Excel. I keep mine in Notepad++.

My workflow is indeed that I only pick up individual components between reinstalls and reorder everything externally.

**Comment by Mycenius** [comment]
Thanks - yes I am doing exactly that . I do all my sorting in Notepad at present once I have the initial sequence. And yes I have Notepad++ and also ConTEXT that I use for more elaborate text work. I've found the upgrades to standard Notepad in Windows 11 make it pretty functional now you can drag and drop, etc, etc... Thanks for the advice.

I'm actually writing up a doc based on my experiences with some tips and tracks and things to watch out for for future 'first time' PI users that I'll share on one of my blogs.
